In [1]:
import numpy as np

#### Write a function that takes a 1d numpy array and computes its reverse vector (last element becomes the first).

In [4]:
def reverse(array):
    return np.flip(array)

a = np.random.uniform(0, 100, 10)
print(a)
print(reverse(a))

[47.29299996 94.80518561 92.51501779 74.99662631 35.04467886 23.87281156
 15.29842322 64.2206305  79.77111916 79.83986409]
[79.83986409 79.77111916 64.2206305  15.29842322 23.87281156 35.04467886
 74.99662631 92.51501779 94.80518561 47.29299996]


#### Given the following square array, compute the product of the elements on its diagonal. [[1 3 8] [-1 3 0] [-3 9 2]]


In [6]:
a = np.array([[1, 3, 8], [-1, 3, 0], [-3, 9, 2]])
print(a.diagonal().prod())

6


#### Create a random vector of size (3, 6) and find its mean value.

In [8]:
a = np.random.uniform(1, 100, (3, 6))
print(a)
print(a.mean())

[[83.70948372  2.45977582 21.46904288 97.65596374 64.33633647 61.37074267]
 [44.55647641 55.37938947  6.12894223 67.67563333 84.31113991 97.85132452]
 [ 2.46032693 88.68680376 86.45068554 71.37033671 80.40278477 47.93165426]]
59.12260239734631


#### Given two arrays a and b, compute how many time an item of a is higher than the corresponding element of b.
##### a: [[1 5 6 8] [2 -3 13 23] [0 -10 -9 7]]
##### b: [[-3 0 8 1] [-20 -9 -1 32] [7 7 7 7]]


In [10]:
a = np.array([[1, 5, 6, 8], [2, -3, 13, 23], [0, -10, -9, 7]])
b = np.array([[-3, 0, 8, 1], [-20, -9, -1, 32], [7, 7, 7, 7]])
print(np.count_nonzero(a > b))

6


#### Create and normalize the following matrix (use min-max normalization). [[0.35 -0.27 0.56] [0.15 0.65 0.42] [0.73 -0.78 -0.08]]

In [12]:
a = np.array([[0.35, -0.27, 0.56], [0.15, 0.65, 0.42], [0.73, -0.78, -0.08]])
norm = (a - a.min()) / (a.max() - a.min())
print(norm)

[[0.74834437 0.33774834 0.88741722]
 [0.61589404 0.94701987 0.79470199]
 [1.         0.         0.46357616]]
